name = "DiodeModels"
uuid = "76b20ad3-5280-4db0-bedf-91ec33f542fc"
authors = ["Stefan de Lange"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
Aqua = "0.8"
DocStringExtensions = "0.8, 0.9"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]

[workspace]
projects = ["test", "docs"]
