name: Lint

"on":
  push:
    branches:
      - main
    tags: ["*"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: read

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v5
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: "1"
      - name: Use Julia cache
        uses: julia-actions/cache@v2
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1
      - name: Install Julia packages
        run: julia -e 'using Pkg; pkg"add JuliaFormatter"'
      - name: Hack for setup-python cache
        run: touch requirements.txt
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          cache: "pip"
          python-version: "3.11"
      - name: Hack for setup-python cache
        run: rm requirements.txt
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: SKIP=no-commit-to-branch pre-commit run -a
