name: ReusableTest

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      os:
        required: true
        type: string
      arch:
        required: true
        type: string
      allow_failure:
        required: false
        type: boolean
        default: false
      run_codecov:
        required: false
        type: boolean
        default: false
    secrets:
      codecov_token:
        required: false

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ inputs.os }}
    continue-on-error: ${{ inputs.allow_failure }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ inputs.version }}
          arch: ${{ inputs.arch }}
      - name: Use Julia cache
        uses: julia-actions/cache@v2
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1
      - name: Run tests
        uses: julia-actions/julia-runtest@v1
      - name: Process coverage
        if: inputs.run_codecov
        uses: julia-actions/julia-processcoverage@v1
      - name: Upload coverage to Codecov
        if: inputs.run_codecov
        uses: codecov/codecov-action@v5
        with:
          file: lcov.info
          token: ${{ secrets.codecov_token }}
